name: Licenses

on:
  workflow_dispatch:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  licences:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Get Repository License
        id: license
        run: |
          license="${{ (github.event.repository.license.spdx_id) || (github.event.repository.licenses[0]) }}"
          echo "License detected: $license"
          echo "license=$license" >> $GITHUB_OUTPUT
      - name: Check Licenses
        uses: ONLYOFFICE/check-licenses@v1
        with:
          project_license: ${{ steps.license.outputs.license }}
